config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "polls#index"

  resource :session
  resources :passwords, param: :token

  scope path_names: { new: "ny", edit: "rediger" } do
    resources :polls, path: "afstemninger"
    resource  :user,  path: "bruger"

    resources :search_agents, path: "søgeagenter"
    resources :email_address_verifications, path: "bekræftelser"
  end

  namespace :oda do
    resources :actors,       path: "aktører"
    resources :deletions
    resources :documents,    path: "dokumenter"
    resources :cases,        path: "sager"
    resources :decisions,    path: "afstemninger"
    resources :descriptions, path: "beskrivelser"
    resources :meetings,     path: "møder"
    resources :periods,      path: "perioder"
    resources :subjects,     path: "emneord"
  end

  namespace :admin do
    root "dashboards#show"
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
end

app/models/oda.rb
module Oda
  def self.table_name_prefix
    "oda_"
  end
end

app/models/oda/afstemning.rb
class Oda::Afstemning < Oda::OdaRecord
  include Synchronizable

  has_many :stemmer
  belongs_to :sagstrin, optional: true
  belongs_to :møde
  belongs_to :type, class_name: "Oda::Afstemningstype"
  has_one :sag,     through: :sagstrin
  has_one :periode, through: :møde

  scope :with_period, ->(period_id) { where(periode: { id: period_id }) }
  scope :chronological, -> { joins(:møde).order(oda_møder: { periode_id: :desc }, nummer: :desc) }
end

app/models/oda/afstemningstype.rb
class Oda::Afstemningstype < Oda::OdaRecord
  include Synchronizable

  has_many :afstemninger, inverse_of: :type
end

app/models/oda/aktør.rb
class Oda::Aktør < Oda::OdaRecord
  include Synchronizable

  has_many :stemmer
  has_many :afstemninger, through: :stemmer

  has_many :fra_aktør_aktører, foreign_key: :fraaktør_id, class_name: "Oda::AktørAktør"
  has_many :til_aktør_aktører, foreign_key: :tilaktør_id, class_name: "Oda::AktørAktør"
  has_many :fraaktører, through: :til_aktør_aktører
  has_many :tilaktører, through: :fra_aktør_aktører

  belongs_to :type, class_name: "Oda::Aktørtype"
  belongs_to :periode, optional: true, counter_cache: true

  scope :alphabetical, -> { order(:navn) }
  scope :chronological, -> { order(opdateringsdato: :desc) }
  scope :matches, ->(search) { where("oda_aktører.navn Like ?", "%#{search}%") if search.present? }
  scope :actortype, ->(id) { joins(:type).where(type: { id: }) }

  def relationer(rolle)
    from = fraaktører.where(oda_aktør_aktører: { rolle_id: rolle.id })
    to   = tilaktører.where(oda_aktør_aktører: { rolle_id: rolle.id })
    (from + to).uniq
  end

  def picture
    nokogiri.css("pictureMiRes").first.content
  rescue
    nil
  end

  def email = nokogiri.css("email").first&.content
  def phone = nokogiri.css("mobilePhone, ministerPhone, phoneFolketinget").first&.content
  def member_data = nokogiri.css("memberData").first&.content&.html_safe

  def nokogiri
    @nokogiri ||= Nokogiri.XML(biografi)
  end
end

app/models/oda/aktør_aktør.rb
class Oda::AktørAktør < Oda::OdaRecord
  include Synchronizable

  belongs_to :rolle, class_name: "Oda::AktørAktørRolle"
  belongs_to :fraaktør, class_name: "Oda::Aktør"
  belongs_to :tilaktør, class_name: "Oda::Aktør"
end

app/models/oda/aktør_aktør_rolle.rb
class Oda::AktørAktørRolle < Oda::OdaRecord
  include Synchronizable

  has_many :aktør_aktører, inverse_of: :rolle
end

app/models/oda/aktørtype.rb
class Oda::Aktørtype < Oda::OdaRecord
  include Synchronizable

  has_many :aktører, inverse_of: :type
end

app/models/oda/dagsordenspunkt.rb
class Oda::Dagsordenspunkt < Oda::OdaRecord
  include Synchronizable

  belongs_to :møde

  # it looks like `super_id` is not used properly
  belongs_to :super, class_name: "Oda::Dagsordenspunkt", optional: true
  belongs_to :sagstrin, optional: true
  has_many :children, class_name: "Oda::Dagsordenspunkt", foreign_key: :super_id
  scope :roots, -> { where(super_id: nil) }
end

app/models/oda/dagsordenspunkt_dokument.rb
class Oda::DagsordenspunktDokument < Oda::OdaRecord
  include Synchronizable
end

app/models/oda/dagsordenspunkt_sag.rb
class Oda::DagsordenspunktSag < Oda::OdaRecord
  include Synchronizable
end

app/models/oda/dokument.rb
class Oda::Dokument < Oda::OdaRecord
  include Synchronizable

  belongs_to :kategori,  class_name: "Oda::Dokumentkategori"
  belongs_to :spørgsmål, class_name: "Oda::Dokument", optional: true
  belongs_to :status,    class_name: "Oda::Dokumentstatus"
  belongs_to :type,      class_name: "Oda::Dokumenttype"

  has_many :filer
  has_many :omtryk
  has_many :sag_dokumenter
  has_many :dokument_aktører
  has_many :emneord_dokumenter
  has_many :sagstrin_dokumenter

  has_many :aktører,  through: :dokument_aktører,    source: :aktør
  has_many :emneord,  through: :emneord_dokumenter,  source: :emneord
  has_many :sager,    through: :sag_dokumenter,      source: :sag
  has_many :sagstrin, through: :sagstrin_dokumenter, source: :sagstrin

  scope :reprinted, -> { joins(:omtryk) }
  scope :chronological, -> { order(opdateringsdato: :desc) }
  scope :matches, ->(search) { where("oda_dokumenter.titel LIKE ?", "%#{search}%") if search.present? }

  scope :with_category, ->(id) { where(kategori_id: id) }
  scope :with_status, ->(id) { where(status_id: id) }
  scope :with_type, ->(id) { where(type_id: id) }
end

app/models/oda/dokument_aktør.rb
class Oda::DokumentAktør < Oda::OdaRecord
  include Synchronizable

  belongs_to :dokument
  belongs_to :aktør
  belongs_to :rolle, class_name: "Oda::DokumentAktørRolle"
end

app/models/oda/dokument_aktør_rolle.rb
class Oda::DokumentAktørRolle < Oda::OdaRecord
  include Synchronizable
end

app/models/oda/dokumentkategori.rb
class Oda::Dokumentkategori < Oda::OdaRecord
  include Synchronizable

  scope :alphabetical, -> { order(:kategori) }
end

app/models/oda/dokumentstatus.rb
class Oda::Dokumentstatus < Oda::OdaRecord
  include Synchronizable

  scope :alphabetical, -> { order(:status) }
end

app/models/oda/dokumenttype.rb
class Oda::Dokumenttype < Oda::OdaRecord
  include Synchronizable

  scope :alphabetical, -> { order(:typenavn) }
end

app/models/oda/emneord.rb
class Oda::Emneord < Oda::OdaRecord
  include Synchronizable

  has_many :emneord_dokumenter, class_name: "Oda::EmneordDokument"
  has_many :dokumenter, through: :emneord_dokumenter, source: :dokument
  has_many :emneord_sager, class_name: "Oda::EmneordSag"
  has_many :sager, through: :emneord_sager, source: :sag

  belongs_to :type, class_name: "Oda::Emneordstype"

  scope :matches, ->(search) { where("oda_emneord.emneord LIKE ?", "%#{search}%") if search.present? }
  scope :subjecttype, ->(id) { where(type_id: id) }

  scope :by_emneord_sager_count, -> { order(emneord_sager_count: :desc) }
end

app/models/oda/emneord_dokument.rb
class Oda::EmneordDokument < Oda::OdaRecord
  include Synchronizable

  belongs_to :dokument, class_name: "Oda::Dokument"
  belongs_to :emneord, class_name: "Oda::Emneord", counter_cache: true
end

app/models/oda/emneord_sag.rb
class Oda::EmneordSag < Oda::OdaRecord
  include Synchronizable

  belongs_to :sag, class_name: "Oda::Sag"
  belongs_to :emneord, class_name: "Oda::Emneord", counter_cache: true
end

app/models/oda/emneordstype.rb
class Oda::Emneordstype < Oda::OdaRecord
  include Synchronizable

  has_many :emneord, inverse_of: :type
end

app/views/oda/documents/index.html.erb
<% content_for(:title) { "Dokumenter" } %>

<header>
  <h1><%= content_for :title %></h1>
  <%= render partial: 'oda/synchronization', locals: { model: Oda::Dokument } %>
</header>

<%= form_with method: :get do |form| %>
  <div>
    <%= form.label :category_id, "Kategori" %>
    <%= form.collection_select :category_id, Oda::Dokumentkategori.alphabetical, :id, :kategori, include_blank: "Alle kategorier", selected: @category_id %>
  </div>

  <div>
    <%= form.label :type_id, "Type" %>
    <%= form.collection_select :type_id, Oda::Dokumenttype.alphabetical, :id, :typenavn, include_blank: "Alle typer", selected: @type_id %>
  </div>

  <div>
    <%= form.label :status_id, "Status" %>
    <%= form.collection_select :status_id, Oda::Dokumentstatus.alphabetical, :id, :status, include_blank: "Alle statuser", selected: @status_id %>
  </div>

  <div>
    <%= check_box_tag :reprinted, checked: params[:reprinted].present? %>
    <%= form.label :reprinted, "Omtrykt" %>
  </div>

  <div>
    <%= form.search_field :search, placeholder: "Fritekst søgning", value: params[:search] %>
    <%= form.submit "Søg" %>
  </div>
<% end %>

<div>
  <table class="table">
    <thead>
      <tr>
        <th>Opdateringsdato</th>
        <th>Titel</th>
        <th>Kategori</th>
        <th>Status</th>
        <th>Type</th>
      </tr>
    </thead>
    <tbody>
      <% @page.records.each do |dokument| %>
        <tr>
          <td><%= l dokument.opdateringsdato, format: :short %></td>
          <td>
            <%= link_to oda_document_path(dokument), title: dokument.titel do %>
              <% if params[:search] %>
                <%= highlight(excerpt(dokument.titel, params[:search], radius: 30), params[:search]) %>
              <% else %>
                <%= truncate(dokument.titel, length: 60) %>
              <% end %>
            <% end %>
          </td>
          <td><%= dokument.kategori.kategori %></td>
          <td><%= dokument.status.status %></td>
          <td><%= dokument.type.typenavn %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render partial: 'oda/pagination' %>

app/views/oda/documents/show.html.erb
<% content_for(:title) { @dokument.titel } %>

<header>
  <%= link_to "← Dokumenter", oda_documents_path %>
  <h1><%= content_for :title %></h1>
  <p>Sidst opdateret for <%= time_ago_in_words @dokument.opdateringsdato %> siden</p>
</header>

<div>
<p>
  <strong>Type:</strong> <%= @dokument.type.typenavn %>
  /
  <strong>Kategori:</strong> <%= @dokument.kategori.kategori %>
  /
  <strong>Status:</strong> <%= @dokument.status.status %>
</p>

<% unless @dokument.omtryk.empty? %>
  <h2>Omtryk</h2>
  <ul>
    <% @dokument.omtryk.each do |omtryk| %>
      <li><%= l omtryk.dato, format: :long %>: <%= omtryk.begrundelse %></li>
    <% end %>
  </ul>
<% end %>

<% unless @dokument.dokument_aktører.empty? %>
  <h2>Aktører</h2>
  <ul>
    <% @dokument.dokument_aktører.each do |dokument_aktør| %>
      <li>
        <%= dokument_aktør.rolle.rolle %>:
        <%= link_to oda_actor_path(dokument_aktør.aktør) do %>
          <%= dokument_aktør.aktør.navn %>
        <% end %>
      </li>
    <% end %>
  </ul>
<% end %>

<h2>Sager</h2>
<ul>
  <% @dokument.sager.each do |sag| %>
    <li><%= link_to sag.titel, oda_case_path(sag) %></li>
  <% end %>
</ul>

<% unless @dokument.sagstrin.empty? %>
  <h3>Sagstrin</h3>
  <ul>
    <% @dokument.sagstrin.each do |sagstrin| %>
      <li><%= link_to sagstrin.titel, oda_case_path(sagstrin.sag_id) %></li>
    <% end %>
  </ul>
<% end %>

<h2>Filer</h2>
<ul>
  <% @dokument.filer.each do |fil| %>
    <li>
      <%= link_to fil.filurl do %>
        <%= fil.titel %> (<%= fil.format %>)
      <% end %>
    </li>
  <% end %>
</ul>

<% unless @dokument.emneord.empty? %>
  <h2>Emneord</h2>
  <ul>
    <% @dokument.emneord.each do |emneord| %>
      <li><%= link_to emneord.emneord, oda_subject_path(emneord) %></li>
    <% end %>
  </ul>
<% end %>
</div>

<%= json_details @dokument %>