config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "polls#index"

  resource :session
  resources :passwords, param: :token

  scope path_names: { new: "ny", edit: "rediger" } do
    resources :polls, path: "afstemninger"
    resource  :user,  path: "bruger"

    resources :search_agents, path: "søgeagenter"
    resources :email_address_verifications, path: "bekræftelser"
  end

  namespace :oda do
    resources :actors,       path: "aktører"
    resources :deletions
    resources :documents,    path: "dokumenter"
    resources :cases,        path: "sager"
    resources :decisions,    path: "afstemninger"
    resources :descriptions, path: "beskrivelser"
    resources :meetings,     path: "møder"
    resources :periods,      path: "perioder"
    resources :subjects,     path: "emneord"
  end

  namespace :admin do
    root "dashboards#show"
    mount MissionControl::Jobs::Engine, at: "/jobs"
  end
end

app/models/oda.rb
module Oda
  def self.table_name_prefix
    "oda_"
  end
end

app/models/oda/afstemning.rb
class Oda::Afstemning < Oda::OdaRecord
  include Synchronizable

  has_many :stemmer
  belongs_to :sagstrin, optional: true
  belongs_to :møde
  belongs_to :type, class_name: "Oda::Afstemningstype"
  has_one :sag,     through: :sagstrin
  has_one :periode, through: :møde

  scope :with_period, ->(period_id) { where(periode: { id: period_id }) }
  scope :chronological, -> { joins(:møde).order(oda_møder: { periode_id: :desc }, nummer: :desc) }
end

app/models/oda/afstemningstype.rb
class Oda::Afstemningstype < Oda::OdaRecord
  include Synchronizable

  has_many :afstemninger, inverse_of: :type
end

app/models/oda/aktør.rb
class Oda::Aktør < Oda::OdaRecord
  include Synchronizable

  has_many :stemmer
  has_many :afstemninger, through: :stemmer

  has_many :fra_aktør_aktører, foreign_key: :fraaktør_id, class_name: "Oda::AktørAktør"
  has_many :til_aktør_aktører, foreign_key: :tilaktør_id, class_name: "Oda::AktørAktør"
  has_many :fraaktører, through: :til_aktør_aktører
  has_many :tilaktører, through: :fra_aktør_aktører

  belongs_to :type, class_name: "Oda::Aktørtype"
  belongs_to :periode, optional: true, counter_cache: true

  scope :alphabetical, -> { order(:navn) }
  scope :chronological, -> { order(opdateringsdato: :desc) }
  scope :matches, ->(search) { where("oda_aktører.navn Like ?", "%#{search}%") if search.present? }
  scope :actortype, ->(id) { joins(:type).where(type: { id: }) }

  def relationer(rolle)
    from = fraaktører.where(oda_aktør_aktører: { rolle_id: rolle.id })
    to   = tilaktører.where(oda_aktør_aktører: { rolle_id: rolle.id })
    (from + to).uniq
  end

  def picture
    nokogiri.css("pictureMiRes").first.content
  rescue
    nil
  end

  def email = nokogiri.css("email").first&.content
  def phone = nokogiri.css("mobilePhone, ministerPhone, phoneFolketinget").first&.content
  def member_data = nokogiri.css("memberData").first&.content&.html_safe

  def nokogiri
    @nokogiri ||= Nokogiri.XML(biografi)
  end
end

app/models/oda/aktør_aktør.rb
class Oda::AktørAktør < Oda::OdaRecord
  include Synchronizable

  belongs_to :rolle, class_name: "Oda::AktørAktørRolle"
  belongs_to :fraaktør, class_name: "Oda::Aktør"
  belongs_to :tilaktør, class_name: "Oda::Aktør"
end

app/models/oda/aktør_aktør_rolle.rb
class Oda::AktørAktørRolle < Oda::OdaRecord
  include Synchronizable

  has_many :aktør_aktører, inverse_of: :rolle
end

app/models/oda/aktørtype.rb
class Oda::Aktørtype < Oda::OdaRecord
  include Synchronizable

  has_many :aktører, inverse_of: :type
end

app/models/oda/dagsordenspunkt.rb
class Oda::Dagsordenspunkt < Oda::OdaRecord
  include Synchronizable

  belongs_to :møde

  # it looks like `super_id` is not used properly
  belongs_to :super, class_name: "Oda::Dagsordenspunkt", optional: true
  belongs_to :sagstrin, optional: true
  has_many :children, class_name: "Oda::Dagsordenspunkt", foreign_key: :super_id
  scope :roots, -> { where(super_id: nil) }
end

app/models/oda/dagsordenspunkt_dokument.rb
class Oda::DagsordenspunktDokument < Oda::OdaRecord
  include Synchronizable
end

app/models/oda/dagsordenspunkt_sag.rb
class Oda::DagsordenspunktSag < Oda::OdaRecord
  include Synchronizable
end

app/models/oda/dokument.rb
class Oda::Dokument < Oda::OdaRecord
  include Synchronizable

  belongs_to :kategori,  class_name: "Oda::Dokumentkategori"
  belongs_to :spørgsmål, class_name: "Oda::Dokument", optional: true
  belongs_to :status,    class_name: "Oda::Dokumentstatus"
  belongs_to :type,      class_name: "Oda::Dokumenttype"

  has_many :filer
  has_many :omtryk
  has_many :sag_dokumenter
  has_many :dokument_aktører
  has_many :emneord_dokumenter
  has_many :sagstrin_dokumenter

  has_many :aktører,  through: :dokument_aktører,    source: :aktør
  has_many :emneord,  through: :emneord_dokumenter,  source: :emneord
  has_many :sager,    through: :sag_dokumenter,      source: :sag
  has_many :sagstrin, through: :sagstrin_dokumenter, source: :sagstrin

  scope :reprinted, -> { joins(:omtryk) }
  scope :chronological, -> { order(opdateringsdato: :desc) }
  scope :matches, ->(search) { where("oda_dokumenter.titel LIKE ?", "%#{search}%") if search.present? }

  scope :with_category, ->(id) { where(kategori_id: id) }
  scope :with_status, ->(id) { where(status_id: id) }
  scope :with_type, ->(id) { where(type_id: id) }
end

app/models/oda/dokument_aktør.rb
class Oda::DokumentAktør < Oda::OdaRecord
  include Synchronizable

  belongs_to :dokument
  belongs_to :aktør
  belongs_to :rolle, class_name: "Oda::DokumentAktørRolle"
end

app/models/oda/dokument_aktør_rolle.rb
class Oda::DokumentAktørRolle < Oda::OdaRecord
  include Synchronizable
end

app/models/oda/dokumentkategori.rb
class Oda::Dokumentkategori < Oda::OdaRecord
  include Synchronizable

  scope :alphabetical, -> { order(:kategori) }
end

app/models/oda/dokumentstatus.rb
class Oda::Dokumentstatus < Oda::OdaRecord
  include Synchronizable

  scope :alphabetical, -> { order(:status) }
end

app/models/oda/dokumenttype.rb
class Oda::Dokumenttype < Oda::OdaRecord
  include Synchronizable

  scope :alphabetical, -> { order(:typenavn) }
end

app/models/oda/emneord.rb
class Oda::Emneord < Oda::OdaRecord
  include Synchronizable

  has_many :emneord_dokumenter, class_name: "Oda::EmneordDokument"
  has_many :dokumenter, through: :emneord_dokumenter, source: :dokument
  has_many :emneord_sager, class_name: "Oda::EmneordSag"
  has_many :sager, through: :emneord_sager, source: :sag

  belongs_to :type, class_name: "Oda::Emneordstype"

  scope :matches, ->(search) { where("oda_emneord.emneord LIKE ?", "%#{search}%") if search.present? }
  scope :subjecttype, ->(id) { where(type_id: id) }

  scope :by_emneord_sager_count, -> { order(emneord_sager_count: :desc) }
end

app/models/oda/emneord_dokument.rb
class Oda::EmneordDokument < Oda::OdaRecord
  include Synchronizable

  belongs_to :dokument, class_name: "Oda::Dokument"
  belongs_to :emneord, class_name: "Oda::Emneord", counter_cache: true
end

app/models/oda/emneord_sag.rb
class Oda::EmneordSag < Oda::OdaRecord
  include Synchronizable

  belongs_to :sag, class_name: "Oda::Sag"
  belongs_to :emneord, class_name: "Oda::Emneord", counter_cache: true
end

app/models/oda/emneordstype.rb
class Oda::Emneordstype < Oda::OdaRecord
  include Synchronizable

  has_many :emneord, inverse_of: :type
end

app/views/oda/cases/index.html.erb
<% content_for(:title) { "Sager" } %>

<header>
  <h1><%= content_for :title %></h1>
  <%= render partial: 'oda/synchronization', locals: { model: Oda::Sag } %>
</header>

<menu>
  <li><%= link_to "L | Lovforslag", oda_cases_path(casetype_id: 3) %></li>
  <li><%= link_to "B | Beslutningsforslag", oda_cases_path(casetype_id: 5) %></li>
  <li><%= link_to "S | § 20-spørgsmål", oda_cases_path(casetype_id: 10) %></li>
</menu>

<%= form_with method: :get do |form| %>
  <%= form.search_field :search, value: params[:search] %>

  <%= form.collection_select :casetype_id, Oda::Sagstype.all, :id, :typenavn, include_blank: "Alle sagstyper", selected: @casetype_id %>

  <%= form.submit "Søg" %>
<% end %>

<div>
  <table class="table">
    <thead>
      <tr>
        <th colspan="3">Sagsnr</th>
        <th>Titel (kort)</th>
        <th>Opdateret</th>
        <th>Status</th>
      </tr>
    </thead>
    <tbody>
      <% @page.records.each do |sag| %>
        <tr>
          <td><%= sag.periode.kode %></td>
          <td><%= sag.nummerprefix %></td>
          <td><%= sag.nummernumerisk %></td>
          <td>
            <%= link_to oda_case_path(sag), title: sag.titel do %>
              <% if params[:search].present? %>
                <%= highlight(excerpt(sag.titel, params[:search], radius: 30), params[:search]) %>
              <% else %>
                <%= truncate(sag.titel, length: 60) %>
              <% end %>
            <% end %>
          </td>
          <td>
            <strong><%= l sag.opdateringsdato, format: :short %></strong>
          </td>
          <td><%= sag.status.status %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= render partial: 'oda/pagination' %>

app/views/oda/cases/show.html.erb
<% content_for(:title) { "#{@sag.titelkort}" } %>

<% @sag.emneord.each do |emneord| %>
  <span class="tag"><%= link_to emneord.emneord, oda_subject_path(emneord) %></span>
<% end %>
<h1 class="title"><%= content_for :title %></h1>
<p class="subtitle"><%= @sag.titel %></p>

<div>
  <p>Resume: <%= sanitize @sag.resume %></p>
  <p><em><%= @sag.afstemningskonklusion %></em></p>

  <% if @sag.deltundersag %>
    <p>Delt under <%= link_to @sag.deltundersag.titelkort, oda_case_path(@sag.deltundersag) %></p>
  <% end %>
  <% if @sag.fremsatundersag %>
    <p>Fremsat under <%= link_to @sag.fremsatundersag.titelkort, oda_case_path(@sag.fremsatundersag) %></p>
  <% end %>

  <h2>Sagstrin</h2>
</div>

<div>
  <table class="table">
    <thead>
      <tr>
        <th>Dato</th>
        <th>Type</th>
        <th>Status</th>
        <th>Sambehandling(er)</th>
        <th>Afstemning</th>
        <th>Dokumenter</th>
      </tr>
    </thead>
    <tbody>
      <% @sagstrin.each do |sagstrin| %>
        <tr>
          <td><strong><%= l sagstrin.dato.to_date, format: :short if sagstrin.dato %></strong></td>
          <td><%= sagstrin.type.typenavn %></td>
          <td><%= sagstrin.status.status %></td>
          <td>
            <ul>
              <% sagstrin.sambehandlinger.each do |sambehandling| %>
                <li><%= link_to sambehandling.titelkort, oda_case_path(sambehandling.id) %></li>
              <% end %>
              </ul>
          </td>
          <td>
            <% if sagstrin.afstemning %>
              <%= link_to "Afstemning", oda_decision_path(sagstrin.afstemning) %>
            <% end %>
          </td>
          <td>
            <ul>
              <% sagstrin.dokumenter.each do |dokument| %>
                <li><%= link_to truncate(dokument.titel), oda_document_path(dokument), title: dokument.titel %></li>
              <% end %>
            </ul>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div>
  <h2>Dokumenter</h2>
</div>

<div>
  <table class="table">
    <thead>
      <tr>
        <th>Bilag#</th>
        <th>Dokument</th>
        <th>Frigivelsesdato</th>
        <th>Rolle</th>
      </tr>
    </thead>
    <tbody>
      <% @sag_dokumenter.each do |sag_dokument| %>
        <tr>
          <td><%= sag_dokument.bilagsnummer %></td>
          <td><%= link_to truncate(sag_dokument.dokument.titel), oda_document_path(sag_dokument.dokument), title: sag_dokument.dokument.titel if sag_dokument.dokument %></td>
          <td><%= l sag_dokument.frigivelsesdato.to_date, format: :long if sag_dokument.frigivelsesdato %></td>
          <td><%= sag_dokument.rolle.rolle %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<%= json_details @sag %>